[
  {
    "TestCaseID": "TC001",
    "Title": "Request OTP with valid registered mobile number",
    "Precondition": "User is on the OTP request page and has a registered mobile number in the system.",
    "Steps": "1. Enter a valid registered mobile number on the OTP request page.\n2. Submit the OTP request.\n3. Verify that the system generates a unique 6-digit OTP.\n4. Check that the OTP is sent to the phone via SMS.\n5. Confirm that a success confirmation message is displayed.",
    "ExpectedResult": "A unique 6-digit OTP is generated and sent to the registered mobile number via SMS; the confirmation message appears on the screen."
  },
  {
    "TestCaseID": "TC002",
    "Title": "Request OTP with valid registered email address",
    "Precondition": "User is on the OTP request page and has a registered email address in the system.",
    "Steps": "1. Enter a valid registered email address on the OTP request page.\n2. Submit the OTP request.\n3. Verify that the system generates a unique 6-digit OTP.\n4. Check that the OTP is sent to the correct email address.\n5. Confirm that a success confirmation message is displayed.",
    "ExpectedResult": "A unique 6-digit OTP is generated and sent to the registered email address; the confirmation message appears on the screen."
  },
  {
    "TestCaseID": "TC003",
    "Title": "Request OTP with unregistered mobile number",
    "Precondition": "User is on the OTP request page and the mobile number is not registered.",
    "Steps": "1. Enter an unregistered mobile number on the OTP request page.\n2. Submit the OTP request.",
    "ExpectedResult": "The system validates the mobile number and displays an error message indicating that the number is not associated with any user; OTP is not generated or sent."
  },
  {
    "TestCaseID": "TC004",
    "Title": "Request OTP with unregistered email address",
    "Precondition": "User is on the OTP request page and the email address is not registered.",
    "Steps": "1. Enter an unregistered email address on the OTP request page.\n2. Submit the OTP request.",
    "ExpectedResult": "The system validates the email address and displays an error message stating that the email is not associated with any user; OTP is not generated or sent."
  },
  {
    "TestCaseID": "TC005",
    "Title": "Request OTP with invalid mobile number format",
    "Precondition": "User is on the OTP request page.",
    "Steps": "1. Enter a mobile number with an invalid format (e.g., less than required digits or containing letters).\n2. Submit the OTP request.",
    "ExpectedResult": "The system validates the mobile number format and displays a descriptive error message (e.g., 'Invalid mobile number format'); no OTP is generated."
  },
  {
    "TestCaseID": "TC006",
    "Title": "Request OTP with invalid email address format",
    "Precondition": "User is on the OTP request page.",
    "Steps": "1. Enter an email address with an invalid format (e.g., missing '@' symbol or domain).\n2. Submit the OTP request.",
    "ExpectedResult": "The system validates the email format and displays a descriptive error message (e.g., 'Invalid email format'); no OTP is generated."
  },
  {
    "TestCaseID": "TC007",
    "Title": "OTP expiration after predefined time",
    "Precondition": "User has successfully requested an OTP and received it via SMS or email.",
    "Steps": "1. Note the time when the OTP is received.\n2. Wait for 5 minutes (or the system defined expiration period).\n3. Attempt to use the OTP after the expiration period.",
    "ExpectedResult": "The OTP is rejected because it has expired; the user is notified that the OTP is no longer valid."
  },
  {
    "TestCaseID": "TC008",
    "Title": "Request OTP exceeding retry limit (Throttling)",
    "Precondition": "User is on the OTP request page and has already requested OTPs up to the system-defined limit within the timeframe.",
    "Steps": "1. Request an OTP repeatedly until reaching the allowed limit.\n2. Attempt to request another OTP immediately after reaching the limit.",
    "ExpectedResult": "The system prevents further OTP requests and displays an error message indicating that the retry limit has been exceeded."
  },
  {
    "TestCaseID": "TC009",
    "Title": "Ensure generated OTP is unique per request",
    "Precondition": "User is on the OTP request page with registered contact information.",
    "Steps": "1. Request an OTP and record the obtained 6-digit code.\n2. Request another OTP after a short interval.\n3. Compare the two OTPs.",
    "ExpectedResult": "Each OTP generated by the system is unique and different from previous OTPs even for the same user."
  },
  {
    "TestCaseID": "TC010",
    "Title": "Handle backend failure for SMS/email service",
    "Precondition": "Simulate an outage or failure in the SMS/email service.",
    "Steps": "1. Request an OTP using a valid registered mobile number or email address.\n2. During the OTP generation and delivery process, simulate a failure in the SMS/email service backend.\n3. Observe system behavior.",
    "ExpectedResult": "The system handles the backend failure gracefully, displaying a user-friendly error message indicating a temporary issue with OTP delivery, and logs the error for further investigation."
  }
]